<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTP11" failures="1" tests="4" name="AAS Login Test" time="9.258" errors="0" timestamp="22 Aug 2020 11:16:28 GMT">
  <testcase classname="AASProductTestCase.AASProductTest.qa.testcases.LoginPageTest" name="LoginPageTitleTest" time="0.01"/>
  <testcase classname="AASProductTestCase.AASProductTest.qa.testcases.LoginPageTest" name="loginTestNegative01" time="1.105">
    <failure type="java.lang.AssertionError" message="expected [Account has been locked.] but found [These credentials do not match our records.]">
      <![CDATA[java.lang.AssertionError: expected [Account has been locked.] but found [These credentials do not match our records.]
	at AASProductTestCase.AASProductTest.qa.testcases.LoginPageTest.loginTestNegative01(LoginPageTest.java:42)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- loginTestNegative01 -->
  <testcase classname="AASProductTestCase.AASProductTest.qa.testcases.LoginPageTest" name="loginTestNegative02" time="0.521"/>
  <testcase classname="AASProductTestCase.AASProductTest.qa.testcases.LoginPageTest" name="LoginTest" time="0.483"/>
</testsuite> <!-- AAS Login Test -->
